server:
  port: 7080
  servlet:
    context-path: /deploy

spring:
  application:
    name: app-deploy
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

app:
  directory:
    data: /home/data
    release: /home/release
    logs: /home/logs
  log:
    cleanup:
      enabled: true
      retention-days: 10
      schedule: "0 0 2 * * ?"


