server:
  port: 7080
  servlet:
    context-path: /deploy

spring:
  application:
    name: app-deploy
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/medicare_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: input
  mapper-locations: classpath:mapper/*.xml

app:
  directory:
    workspace: /home/workspace
    archive: /home/archive
    logs: /home/logs
  log:
    cache-size: 100
    flush-size: 10
    flush-interval-minutes: 5
    max-file-size-mb: 20
